name: Release
on:
  push:
    branches:
      - main
      - beta
jobs:
  release:
    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
        env:
          SKIP_YARN_COREPACK_CHECK: '1'
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn
      - name: Publish
        uses: changesets/action@v1
        with:
          title: 'release: version packages'
          commit: 'release: version packages'
          publish: yarn publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
